# Generated by Django 3.0.1 on 2019-12-27 20:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import factory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('version', models.IntegerField()),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
            bases=(factory.models.FieldHelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('version', models.IntegerField()),
                ('locked', models.BooleanField(default=True)),
                ('last_version', models.BooleanField(default=True)),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
            bases=(factory.models.FieldHelperMixin, models.Model),
        ),
    ]
