version: '3'
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5430:5432
    environment:
      POSTGRES_PASSWORD: datastorage
      POSTGRES_USER: datastorage
      POSTGRES_DB: datastorage
    volumes:
      - ~/datastorage_dbdata:/data/pgdata
  rabbitmq:
    image: rabbitmq:3.7-management
    environment:
      RABBITMQ_DEFAULT_USER: sandboxpy
      RABBITMQ_DEFAULT_PASS: sandboxpy
      RABBITMQ_DEFAULT_VHOST: /sandboxpy
    ports:
      - 9172:5672
      - 15672:15672
  redis:
    image: redis:5
    ports:
      - 6379:6379